-- V2__Optimize_Loan_Decisions.sql
-- Optimizes the loan_decisions table for pagination and retention strategy

-- 1. Drop the implicit single-column indexes generated by Hibernate auto-ddl
-- (Note: MySQL syntax. Drop these only if they exist.)
SET @exist = (SELECT COUNT(*) FROM information_schema.statistics WHERE table_name = 'loan_decisions' AND index_name = 'idx_loan_decisions_user_id' AND table_schema = DATABASE());
SET @sql = IF(@exist > 0, 'DROP INDEX idx_loan_decisions_user_id ON loan_decisions', 'SELECT ''Index missing, skipped''');
PREPARE stmt FROM @sql;
EXECUTE stmt;

SET @exist = (SELECT COUNT(*) FROM information_schema.statistics WHERE table_name = 'loan_decisions' AND index_name = 'idx_loan_decisions_decided_at' AND table_schema = DATABASE());
SET @sql = IF(@exist > 0, 'DROP INDEX idx_loan_decisions_decided_at ON loan_decisions', 'SELECT ''Index missing, skipped''');
PREPARE stmt FROM @sql;
EXECUTE stmt;

-- 2. Create the composite index to optimize the paginated fetch (user_id + decided_at DESC)
-- This allows the DB to instantly retrieve the most recent decisions for a user without a separate sorting pass.
CREATE INDEX idx_loan_decisions_user_time ON loan_decisions (user_id, decided_at DESC);

-- The retention strategy is managed programmatically via Spring Boot's @Scheduled task 
-- to ensure application-level control (PredictionService.cleanupOldDecisions). 
-- Alternatively, for native MySQL retention (Event Scheduler), you could use:
/*
DELIMITER $$
CREATE EVENT IF NOT EXISTS cleanup_old_loan_decisions
ON SCHEDULE EVERY 1 DAY
DO
  DELETE FROM loan_decisions WHERE decided_at < NOW() - INTERVAL 90 DAY;
$$
DELIMITER ;
*/
